- src/auth.ts
- src/components/molecules/profile/headerProfileContainer.tsx
- src/utils/setAuthInfo/post.util.ts
- header user info 트랙네임 출력이 되도록 수정
> fix: header user info

- src/app/(rootLayout)/layout.tsx
- src/app/layout.tsx
> [#41]fix: build 오류 해결

- src/app/(rootLayout)/layout.tsx
- src/app/layout.tsx
> [#41] fix: build 오류 해결

- src/app/(rootLayout)/mypage/page.tsx
- src/components/pages/mainPage.tsx
- src/components/pages/myProfile.tsx
> [#46]fix : 마이페이지 간격 수정

- src/components/molecules/postDetail/postDetailHeader.tsx
> fix: post detail back button 오류수정

- .idea/.name
- src/components/molecules/categoryGroup/categoryGroup.tsx
- src/constatns/post.constant.ts
- src/hooks/usePostList.ts
- src/hooks/usePostTypeNames.ts
> [#53] update : category backend data로 변경

- src/components/molecules/postDetail/notionLink.tsx
게시물 디테일 페이지에서 notion 안내 문구 워딩 변경
> update : notion 안내 문구 워딩 변경

- src/api/client/postApi.ts
- src/api/server/postsApi.ts
POST-020 유저의 최근 검색어 조회
POST-012 태그를 클릭하여 검색하는 기능
POST-005 게시물 목록 조회
POST-004 게시물 검색
에 대한 period 명 변경
> update : loginPeriod -> selectPeriod로 변경

- src/app/(rootLayout)/role/result/page.tsx
- src/class/signup.ts
- src/components/molecules/form/PhoneField.tsx
- src/components/molecules/form/PhoneForm.tsx
- src/components/organisms/roleSelectForm.tsx
- src/components/pages/signIn.tsx
- src/components/pages/signUpCompleteModal.tsx
- src/components/pages/signupModal.tsx
- src/hooks/useSignupForm.tsx
- src/validators/auth/signup.validator.ts
> [#65]Update : 닉네임 백엔드에서 자동생성으로 회원가입 로직 수정

- src/components/atoms/helperButton.tsx
- src/components/pages/roleResult/roleWait.tsx
- src/constatns/helpLink.constant.ts
> feat: 문의하기 button 연결

- src/app/(rootLayout)/post/[id]/page.tsx
- src/components/atoms/InputContainer.tsx
- src/components/atoms/PasswordContainer.tsx
- src/components/molecules/form/PhonChangeField.tsx
- src/components/molecules/post/postCard.tsx
- src/components/molecules/postDetail/postDetailHeader.tsx
- src/components/pages/bookMarkPage.tsx
- src/components/pages/postDetailPage.tsx
- src/components/pages/profile/passwordChangeModal.tsx
- src/components/pages/profile/phoneChangeModal.tsx
- src/components/pages/signIn.tsx
> [#71] feat : 상세 페이지 내에서도 북마크 추가

- src/components/molecules/profile/headerProfileContainer.tsx
> [#79]update: header user info 변경

- src/components/molecules/postDetail/morePost.tsx
- src/components/pages/postDetailPage.tsx
> [#82] fix: 더보기 버튼 오류 수정

- src/app/api/auth/lastConnectRole/route.ts
> [#84]feat : 말줄임 표시

- src/components/organisms/searchInput.tsx
- src/components/pages/bookMarkPage.tsx
> [#86] search keyword 255자 이하로 제한

- src/components/molecules/categoryGroup/categoryGroup.tsx
- src/hooks/usePostTypeNames.ts
> [#89] category 분리

- src/components/pages/bookMarkPage.tsx
- src/components/pages/signIn.tsx
- tailwind.config.ts
> [#87]Update : 로그인 대시보드 이미지 수정

- src/components/atoms/modal.tsx
- src/components/molecules/postDetail/notionContainer.tsx
- src/components/pages/bookMarkPage.tsx
- src/components/pages/myProfile.tsx
- src/components/pages/progressModal.tsx
- src/components/pages/selectAccountPage.tsx
- src/middleware.ts
> [#94] loading progress 적용

- src/api/bookmark/keys.constant.ts
- src/api/bookmark/useMutation.ts
- src/components/pages/bookMarkPage.tsx
> [#93] Fix : 북마크 전체 삭제 모달 문구 수정

- src/components/organisms/searchInput.tsx
최근 검색어로 검색 클릭 후 dropdown close 추가
> [#97] 최근 검색어로 검색 클릭 후 dropdown close 추가

- src/components/molecules/profile/headerProfileContainer.tsx
- src/hooks/usePostList.ts
home에서 filtering 후 detail접속 후 뒤로가기 하면 tutor filter 표기 오류
> [#99] home에서 filtering 후 detail접속 후 뒤로가기 하면 tutor filter 표기 오류

- src/components/atoms/profileLayout.tsx
- src/components/pages/myProfile.tsx
> [#101] Fix : 마이페이지 UI 수정

- src/api/server/postsApi.ts
- src/app/(rootLayout)/role/result/page.tsx
- src/utils/axios/serverAxios.ts
> [#107] fix: refresh token logic 변경
